### ISSUE TITLE
Check if the bootstrap instructions still work

### ISSUE THREAD

**Issue by watson** [elastic/opbeans-node#31]
The bootstrap instructions in the README are very old and have not been tested for ages. We should consider if we should just remove them and add notes to the docs about how to run this with Docker instead maybe

**Comment by dbvrac** [comment]
I cloned a fresh project, created a Postgres database, ran through the Bootstrap instructions, verified that db-setup populated the database, and I can't get it to work. What am I missing?
Thanks in advance

Console output from `npm start`:
`Elastic APM agent is inactive due to configuration
server is listening on port 3000
logging error 675f995a-b55b-4d19-9bd4-39544c3ddce6 with Elastic APM
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
Application encountered an uncaught exception. Flushing Elastic APM queue and exiting...
Elastic APM queue flushed!`

Here is the npm log file:
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.11.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle opbeans-node@1.0.0~prestart: opbeans-node@1.0.0
6 info lifecycle opbeans-node@1.0.0~start: opbeans-node@1.0.0
7 verbose lifecycle opbeans-node@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle opbeans-node@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/x/x/x/opbeans-node/node_modules/.bin:/Users/x/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin
9 verbose lifecycle opbeans-node@1.0.0~start: CWD: /Users/x/x/x/opbeans-node
10 silly lifecycle opbeans-node@1.0.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle opbeans-node@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle opbeans-node@1.0.0~start: Failed to exec start script
13 verbose stack Error: opbeans-node@1.0.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid opbeans-node@1.0.0
15 verbose cwd /Users/db/WebstormProjects/testApps/opbeans-node
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/10.11.0/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.11.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error opbeans-node@1.0.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the opbeans-node@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`
